// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Data
{

public enum ClientType : byte
{
  NONE = 0,
  Person = 1,
  Group = 2,
};


}
